using System;
using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public enum ObjectCollisionBoxCategory
{
    Skip = 0,
    Chair = 1,
    Seating = 2,
    Table = 3,
    Cabinet = 4,
    Bed = 5,
    Piano = 6,
    Plant = 7,
    Clock = 8,
    GenericFloorObject = 9
}

public readonly struct ObjectCollisionFootprint
{
    public readonly ObjectCollisionBoxCategory Category;
    public readonly Rect WorldRect;
    public readonly float HeightFraction;
    public readonly string Note;

    public ObjectCollisionFootprint(
        ObjectCollisionBoxCategory category,
        Rect worldRect,
        float heightFraction,
        string note)
    {
        Category = category;
        WorldRect = worldRect;
        HeightFraction = Mathf.Max(0.001f, heightFraction);
        Note = note ?? string.Empty;
    }
}

public sealed class ObjectCollisionBoxAuthoringWindow : EditorWindow
{
    private Vector2 scrollPosition;
    private readonly List<ObjectCollisionBoxAuthoring.ScanResult> scanResults = new List<ObjectCollisionBoxAuthoring.ScanResult>();
    private string status = "Run a dry scan before generating blockers.";

    [MenuItem("Dreadforge/Object Collision/Collision Box Authoring")]
    public static void Open()
    {
        GetWindow<ObjectCollisionBoxAuthoringWindow>("Object Collision");
    }

    [MenuItem("Dreadforge/Object Collision/Dry Run Object Collision Boxes")]
    public static void DryRunMenu()
    {
        List<ObjectCollisionBoxAuthoring.ScanResult> results = ObjectCollisionBoxAuthoring.ScanActiveScene();
        Debug.Log(ObjectCollisionBoxAuthoring.BuildScanReport(results));
    }

    [MenuItem("Dreadforge/Object Collision/Generate Missing PlayerBlockers")]
    public static void GenerateMenu()
    {
        int created = ObjectCollisionBoxAuthoring.GenerateMissingPlayerBlockersForActiveScene();
        Debug.Log($"Generated or synced {created} PlayerBlocker object collision box(es).");
    }

    private void OnGUI()
    {
        EditorGUILayout.LabelField("Object Collision Box Authoring", EditorStyles.boldLabel);
        EditorGUILayout.HelpBox(
            "Movement blockers should describe the object's floor-contact footprint, not the whole painted image. A chair blocks around legs/seat base; its backrest belongs to occlusion sorting, not no-walk collision. Generate / Sync also makes each blocker sort its source SpriteRenderer props from the same footprint.",
            MessageType.Info);

        using (new EditorGUILayout.HorizontalScope())
        {
            if (GUILayout.Button("Dry Run"))
            {
                scanResults.Clear();
                scanResults.AddRange(ObjectCollisionBoxAuthoring.ScanActiveScene());
                status = $"Found {ObjectCollisionBoxAuthoring.CountGeneratable(scanResults)} candidate blocker(s).";
            }

            if (GUILayout.Button("Generate / Sync PlayerBlockers"))
            {
                int created = ObjectCollisionBoxAuthoring.GenerateMissingPlayerBlockersForActiveScene();
                scanResults.Clear();
                scanResults.AddRange(ObjectCollisionBoxAuthoring.ScanActiveScene());
                status = $"Generated or synced {created} blocker(s).";
            }

            if (GUILayout.Button("Delete Generated PlayerBlockers"))
            {
                if (EditorUtility.DisplayDialog(
                    "Delete generated blockers?",
                    "Delete only ObjectMovementBlocker2D objects generated by this collision box tool in the active scene?",
                    "Delete Generated",
                    "Cancel"))
                {
                    int deleted = ObjectCollisionBoxAuthoring.DeleteGeneratedPlayerBlockersInActiveScene();
                    scanResults.Clear();
                    status = $"Deleted {deleted} generated blocker(s).";
                }
            }
        }

        EditorGUILayout.LabelField(status, EditorStyles.miniBoldLabel);
        EditorGUILayout.Space(6f);
        EditorGUILayout.LabelField("Dry Run Results", EditorStyles.boldLabel);

        scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition);

        if (scanResults.Count == 0)
        {
            EditorGUILayout.LabelField("No scan results yet.");
        }
        else
        {
            for (int i = 0; i < scanResults.Count; i++)
            {
                ObjectCollisionBoxAuthoring.ScanResult result = scanResults[i];
                EditorGUILayout.LabelField(
                    $"{result.RoomName}: {result.SourceName}",
                    result.ShouldGenerate ? EditorStyles.boldLabel : EditorStyles.label);
                EditorGUILayout.LabelField($"{result.Category} - {result.Reason}");
            }
        }

        EditorGUILayout.EndScrollView();
    }
}

public static class ObjectCollisionBoxAuthoring
{
    private const string GameplayScenePath = "Assets/Scenes/Gameplay.unity";
    private const string PlayerBlockerPrefix = "PlayerBlocker_";
    private const float MinimumFootprintSize = 0.02f;

    public readonly struct ScanResult
    {
        public readonly RoomContentGroup Room;
        public readonly GameObject Source;
        public readonly string RoomName;
        public readonly string SourceName;
        public readonly ObjectCollisionBoxCategory Category;
        public readonly bool ShouldGenerate;
        public readonly bool AlreadyHasBlocker;
        public readonly string Reason;
        public readonly ObjectCollisionFootprint Footprint;

        public ScanResult(
            RoomContentGroup room,
            GameObject source,
            ObjectCollisionBoxCategory category,
            bool shouldGenerate,
            bool alreadyHasBlocker,
            string reason,
            ObjectCollisionFootprint footprint)
        {
            Room = room;
            Source = source;
            RoomName = room != null ? room.RoomName : string.Empty;
            SourceName = source != null ? source.name : string.Empty;
            Category = category;
            ShouldGenerate = shouldGenerate;
            AlreadyHasBlocker = alreadyHasBlocker;
            Reason = reason ?? string.Empty;
            Footprint = footprint;
        }
    }

    private readonly struct FootprintRule
    {
        public readonly ObjectCollisionBoxCategory Category;
        public readonly float XInsetFraction;
        public readonly float HeightFraction;
        public readonly string Note;

        public FootprintRule(
            ObjectCollisionBoxCategory category,
            float xInsetFraction,
            float heightFraction,
            string note)
        {
            Category = category;
            XInsetFraction = Mathf.Clamp01(xInsetFraction);
            HeightFraction = Mathf.Clamp01(heightFraction);
            Note = note;
        }
    }

    public static bool TryCreateFootprintFromBounds(
        string objectName,
        Bounds visualBounds,
        out ObjectCollisionFootprint footprint)
    {
        footprint = default;

        if (!TryGetRule(objectName, out FootprintRule rule))
        {
            return false;
        }

        if (visualBounds.size.x <= MinimumFootprintSize || visualBounds.size.y <= MinimumFootprintSize)
        {
            return false;
        }

        float width = visualBounds.size.x;
        float height = visualBounds.size.y;
        float xInset = width * rule.XInsetFraction;
        float rectWidth = Mathf.Max(MinimumFootprintSize, width - (xInset * 2f));
        float rectHeight = Mathf.Max(MinimumFootprintSize, height * rule.HeightFraction);
        float xMin = visualBounds.min.x + xInset;
        float yMin = visualBounds.min.y;
        Rect rect = new Rect(xMin, yMin, rectWidth, rectHeight);

        footprint = new ObjectCollisionFootprint(rule.Category, rect, rule.HeightFraction, rule.Note);
        return true;
    }

    public static List<ScanResult> ScanActiveScene()
    {
        List<ScanResult> results = new List<ScanResult>();
        RoomContentGroup[] rooms = FindSceneObjects<RoomContentGroup>();

        for (int roomIndex = 0; roomIndex < rooms.Length; roomIndex++)
        {
            RoomContentGroup room = rooms[roomIndex];

            if (room == null || string.IsNullOrWhiteSpace(room.RoomName))
            {
                continue;
            }

            Transform[] children = room.GetComponentsInChildren<Transform>(true);

            for (int childIndex = 0; childIndex < children.Length; childIndex++)
            {
                Transform child = children[childIndex];

                if (child == null || child == room.transform)
                {
                    continue;
                }

                GameObject source = child.gameObject;

                if (!IsPotentialSourceObject(source, out string skipReason))
                {
                    if (ShouldReportSkippedObject(source.name))
                    {
                        results.Add(new ScanResult(room, source, ObjectCollisionBoxCategory.Skip, false, false, skipReason, default));
                    }

                    continue;
                }

                if (!TryGetVisualBounds(source, out Bounds bounds) ||
                    !TryCreateFootprintFromBounds(source.name, bounds, out ObjectCollisionFootprint footprint))
                {
                    continue;
                }

                bool alreadyHasBlocker = HasExistingGeneratedOrNamedBlocker(room.transform, source.name);
                results.Add(new ScanResult(
                    room,
                    source,
                    footprint.Category,
                    !alreadyHasBlocker,
                    alreadyHasBlocker,
                    alreadyHasBlocker ? "matching PlayerBlocker already exists" : footprint.Note,
                    footprint));
            }
        }

        return results;
    }

    public static int CountGeneratable(IReadOnlyList<ScanResult> results)
    {
        int count = 0;

        for (int i = 0; i < results.Count; i++)
        {
            if (results[i].ShouldGenerate)
            {
                count++;
            }
        }

        return count;
    }

    public static string BuildScanReport(IReadOnlyList<ScanResult> results)
    {
        StringBuilder builder = new StringBuilder();
        builder.AppendLine("Object Collision Box Dry Run");
        builder.AppendLine("Rule: physical blocker equals floor-contact footprint, never full sprite/image bounds.");
        builder.AppendLine();

        for (int i = 0; i < results.Count; i++)
        {
            ScanResult result = results[i];
            string action = result.ShouldGenerate ? "GENERATE" : result.AlreadyHasBlocker ? "EXISTS" : "SKIP";
            builder.AppendLine($"{action}: {result.RoomName} / {result.SourceName} / {result.Category} / {result.Reason}");
        }

        builder.AppendLine();
        builder.AppendLine($"Generatable: {CountGeneratable(results)}");
        return builder.ToString();
    }

    public static int GenerateMissingPlayerBlockersForActiveScene()
    {
        List<ScanResult> results = ScanActiveScene();
        int changed = 0;

        for (int i = 0; i < results.Count; i++)
        {
            ScanResult result = results[i];

            if ((!result.ShouldGenerate && !result.AlreadyHasBlocker) ||
                result.Room == null ||
                result.Source == null)
            {
                continue;
            }

            CreateOrUpdatePlayerBlocker(result.Room, result.Source, result.Footprint);
            changed++;
        }

        if (changed > 0)
        {
            EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
        }

        return changed;
    }

    [MenuItem("Dreadforge/Object Collision/Sync Gameplay PlayerBlocker Sorting")]
    public static void SyncGameplayScenePlayerBlockerSorting()
    {
        int changed = SyncScenePlayerBlockerSorting(GameplayScenePath, true);
        Debug.Log($"Synced {changed} Gameplay PlayerBlocker sorting reference(s).");
    }

    public static int SyncScenePlayerBlockerSorting(string scenePath, bool saveScene)
    {
        if (string.IsNullOrWhiteSpace(scenePath))
        {
            Debug.LogError("Cannot sync object collision sorting because the scene path is empty.");
            return 0;
        }

        Scene openedScene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
        int changed = GenerateMissingPlayerBlockersForActiveScene();

        if (saveScene && changed > 0)
        {
            EditorSceneManager.SaveScene(openedScene);
        }

        return changed;
    }

    public static PolygonCollider2D CreateOrUpdatePlayerBlocker(
        RoomContentGroup room,
        GameObject source,
        ObjectCollisionFootprint footprint)
    {
        if (room == null)
        {
            throw new ArgumentNullException(nameof(room));
        }

        if (source == null)
        {
            throw new ArgumentNullException(nameof(source));
        }

        string baseName = PlayerBlockerPrefix + SanitizeName(source.name);
        Transform existing = FindExistingBlocker(room.transform, source.name);
        GameObject blockerObject;

        if (existing != null)
        {
            blockerObject = existing.gameObject;
            Undo.RecordObject(blockerObject, "Update object movement blocker");
        }
        else
        {
            blockerObject = new GameObject(GetUniqueChildName(room.transform, baseName));
            Undo.RegisterCreatedObjectUndo(blockerObject, "Create object movement blocker");
            Undo.SetTransformParent(blockerObject.transform, room.transform, "Parent object movement blocker");
        }

        blockerObject.transform.localPosition = Vector3.zero;
        blockerObject.transform.localRotation = Quaternion.identity;
        blockerObject.transform.localScale = Vector3.one;

        PolygonCollider2D collider = blockerObject.GetComponent<PolygonCollider2D>();

        if (collider == null)
        {
            collider = Undo.AddComponent<PolygonCollider2D>(blockerObject);
        }

        Undo.RecordObject(collider, "Update object movement blocker polygon");
        collider.isTrigger = true;
        collider.pathCount = 1;
        collider.SetPath(0, BuildLocalRectPath(blockerObject.transform, footprint.WorldRect));

        ObjectMovementBlocker2D marker = blockerObject.GetComponent<ObjectMovementBlocker2D>();

        if (marker == null)
        {
            marker = Undo.AddComponent<ObjectMovementBlocker2D>(blockerObject);
        }

        Undo.RecordObject(marker, "Update object movement blocker marker");
        marker.Configure(
            source,
            room.RoomName,
            footprint.Category.ToString(),
            footprint.HeightFraction,
            footprint.Note,
            true);

        EditorUtility.SetDirty(blockerObject);
        EditorUtility.SetDirty(collider);
        EditorUtility.SetDirty(marker);
        return collider;
    }

    public static int DeleteGeneratedPlayerBlockersInActiveScene()
    {
        int deleted = 0;
        ObjectMovementBlocker2D[] blockers = FindSceneObjects<ObjectMovementBlocker2D>();

        for (int i = 0; i < blockers.Length; i++)
        {
            ObjectMovementBlocker2D blocker = blockers[i];

            if (blocker == null || !blocker.GeneratedByCollisionBoxTool)
            {
                continue;
            }

            Undo.DestroyObjectImmediate(blocker.gameObject);
            deleted++;
        }

        if (deleted > 0)
        {
            EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
        }

        return deleted;
    }

    private static bool TryGetRule(string objectName, out FootprintRule rule)
    {
        string key = NormalizeName(objectName);

        if (string.IsNullOrEmpty(key) ||
            ContainsAny(key, "player", "guest", "butler", "boundary", "blocker", "trigger", "doorbutton"))
        {
            rule = default;
            return false;
        }

        if (ContainsAny(key, "portrait", "painting", "picture", "frame", "window", "curtain", "wallpaper", "wall", "ceiling", "shadow", "glow", "light", "chandelier", "sconce", "flame", "fire", "smoke", "patch", "overlay"))
        {
            rule = default;
            return false;
        }

        if (ContainsAny(key, "chair", "stool"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Chair, 0.18f, 0.30f, "chair lower legs/seat footprint");
            return true;
        }

        if (ContainsAny(key, "sofa", "couch", "bench", "settee", "ottoman"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Seating, 0.10f, 0.32f, "seating lower base footprint");
            return true;
        }

        if (ContainsAny(key, "table", "desk", "cart"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Table, 0.08f, 0.30f, "table legs/base footprint");
            return true;
        }

        if (ContainsAny(key, "cabinet", "wardrobe", "dresser", "bookshelf", "shelf", "bookcase", "armoire", "sideboard"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Cabinet, 0.03f, 0.26f, "cabinet floor base footprint");
            return true;
        }

        if (ContainsAny(key, "bed"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Bed, 0.05f, 0.42f, "bed lower footprint");
            return true;
        }

        if (ContainsAny(key, "piano"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Piano, 0.06f, 0.35f, "piano lower body footprint");
            return true;
        }

        if (ContainsAny(key, "plant", "vase", "urn", "pot"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Plant, 0.25f, 0.26f, "small floor object base footprint");
            return true;
        }

        if (ContainsAny(key, "clock", "statue", "screen", "lectern", "pedestal"))
        {
            rule = new FootprintRule(ObjectCollisionBoxCategory.Clock, 0.12f, 0.28f, "tall floor object's base footprint");
            return true;
        }

        rule = default;
        return false;
    }

    private static bool IsPotentialSourceObject(GameObject source, out string reason)
    {
        reason = string.Empty;

        if (source == null)
        {
            reason = "missing source";
            return false;
        }

        if (source.GetComponent<ObjectMovementBlocker2D>() != null ||
            source.GetComponent<RoomContentGroup>() != null)
        {
            reason = "authoring/system object";
            return false;
        }

        if (source.GetComponentInParent<RoomProjectedEntity>() != null)
        {
            reason = "projected actor";
            return false;
        }

        string normalized = NormalizeName(source.name);

        if (normalized.StartsWith("playerboundary", StringComparison.Ordinal) ||
            normalized.StartsWith("playerblocker", StringComparison.Ordinal) ||
            normalized.Contains("doortrigger"))
        {
            reason = "navigation object";
            return false;
        }

        if (!TryGetRule(source.name, out _))
        {
            reason = "not a known floor-blocking object";
            return false;
        }

        return true;
    }

    private static bool TryGetVisualBounds(GameObject source, out Bounds bounds)
    {
        bool hasBounds = false;
        bounds = default;

        Renderer[] renderers = source.GetComponentsInChildren<Renderer>(true);

        for (int i = 0; i < renderers.Length; i++)
        {
            Renderer renderer = renderers[i];

            if (renderer == null || renderer is ParticleSystemRenderer)
            {
                continue;
            }

            if (!hasBounds)
            {
                bounds = renderer.bounds;
                hasBounds = true;
            }
            else
            {
                bounds.Encapsulate(renderer.bounds);
            }
        }

        RectTransform[] rectTransforms = source.GetComponentsInChildren<RectTransform>(true);
        Vector3[] corners = new Vector3[4];

        for (int i = 0; i < rectTransforms.Length; i++)
        {
            RectTransform rectTransform = rectTransforms[i];

            if (rectTransform == null || rectTransform.GetComponentInParent<Graphic>() == null)
            {
                continue;
            }

            rectTransform.GetWorldCorners(corners);

            for (int cornerIndex = 0; cornerIndex < corners.Length; cornerIndex++)
            {
                if (!hasBounds)
                {
                    bounds = new Bounds(corners[cornerIndex], Vector3.zero);
                    hasBounds = true;
                }
                else
                {
                    bounds.Encapsulate(corners[cornerIndex]);
                }
            }
        }

        return hasBounds;
    }

    private static Vector2[] BuildLocalRectPath(Transform targetTransform, Rect worldRect)
    {
        return new[]
        {
            WorldToLocal(targetTransform, worldRect.xMin, worldRect.yMin),
            WorldToLocal(targetTransform, worldRect.xMax, worldRect.yMin),
            WorldToLocal(targetTransform, worldRect.xMax, worldRect.yMax),
            WorldToLocal(targetTransform, worldRect.xMin, worldRect.yMax)
        };
    }

    private static Vector2 WorldToLocal(Transform targetTransform, float x, float y)
    {
        Vector3 local = targetTransform.InverseTransformPoint(new Vector3(x, y, 0f));
        return new Vector2(local.x, local.y);
    }

    private static bool HasExistingGeneratedOrNamedBlocker(Transform roomTransform, string sourceName)
    {
        return FindExistingBlocker(roomTransform, sourceName) != null;
    }

    private static Transform FindExistingBlocker(Transform roomTransform, string sourceName)
    {
        string expectedKey = NormalizeName(PlayerBlockerPrefix + SanitizeName(sourceName));
        ObjectMovementBlocker2D[] blockers = roomTransform.GetComponentsInChildren<ObjectMovementBlocker2D>(true);

        for (int i = 0; i < blockers.Length; i++)
        {
            ObjectMovementBlocker2D blocker = blockers[i];

            if (blocker == null)
            {
                continue;
            }

            if (NormalizeName(blocker.SourceObjectName) == NormalizeName(sourceName) ||
                NormalizeName(blocker.name) == expectedKey)
            {
                return blocker.transform;
            }
        }

        Transform[] children = roomTransform.GetComponentsInChildren<Transform>(true);

        for (int i = 0; i < children.Length; i++)
        {
            Transform child = children[i];

            if (child != null && NormalizeName(child.name) == expectedKey)
            {
                return child;
            }
        }

        return null;
    }

    private static string GetUniqueChildName(Transform parent, string baseName)
    {
        string candidate = baseName;
        int suffix = 1;

        while (parent.Find(candidate) != null)
        {
            suffix++;
            candidate = $"{baseName}_{suffix}";
        }

        return candidate;
    }

    private static bool ShouldReportSkippedObject(string objectName)
    {
        string key = NormalizeName(objectName);
        return ContainsAny(key, "chair", "table", "sofa", "bench", "bed", "piano", "desk", "cabinet", "wardrobe", "clock", "plant", "vase", "portrait", "painting", "window", "curtain", "light");
    }

    private static bool ContainsAny(string text, params string[] needles)
    {
        for (int i = 0; i < needles.Length; i++)
        {
            if (text.Contains(needles[i]))
            {
                return true;
            }
        }

        return false;
    }

    private static T[] FindSceneObjects<T>() where T : UnityEngine.Object
    {
#if UNITY_2023_1_OR_NEWER
        return UnityEngine.Object.FindObjectsByType<T>(FindObjectsInactive.Include);
#else
        return UnityEngine.Object.FindObjectsOfType<T>(true);
#endif
    }

    private static string NormalizeName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        StringBuilder builder = new StringBuilder(value.Length);

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];

            if (char.IsLetterOrDigit(c))
            {
                builder.Append(char.ToLowerInvariant(c));
            }
        }

        return builder.ToString();
    }

    private static string SanitizeName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Object";
        }

        StringBuilder builder = new StringBuilder(value.Length);

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];

            if (char.IsLetterOrDigit(c))
            {
                builder.Append(c);
            }
            else if (builder.Length > 0 && builder[builder.Length - 1] != '_')
            {
                builder.Append('_');
            }
        }

        string result = builder.ToString().Trim('_');
        return string.IsNullOrEmpty(result) ? "Object" : result;
    }
}
