#!/usr/bin/env python3
"""Extract Chateau cursor style icons from the approved concept sheet.

The supplied source image has nine visible numbered style columns:
1, 2, 3, 4, 5, 6, 7, 8, and 10. The game menu needs ten selectable
style slots, so style_09 intentionally reuses the visible column 10 art
until a unique column 9 source sheet is available. No new artwork is
generated by this script.
"""

from __future__ import annotations

from collections import deque
from pathlib import Path
from statistics import median
import sys

try:
    from PIL import Image, ImageDraw, ImageFilter, ImageFont
except ImportError as exc:
    raise SystemExit(
        "Pillow is required. Install it with `python3 -m pip install pillow` "
        "or run this script from the temporary cursor icon venv."
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Assets/Art/UI/Cursors/source/vintage_cursor_icon_concept_sheet.png"
OUTPUT_ROOT = ROOT / "Assets/Resources/UI/Cursors/styles"
PREVIEW = ROOT / "Assets/Art/UI/Cursors/preview/cursor_styles_contact_sheet.png"

ICON_SIZE = 72
ICON_INNER_SIZE = 64
CROP_WIDTH = 100
CROP_HEIGHT = 76

VISIBLE_COLUMN_CENTERS = {
    1: 218,
    2: 309,
    3: 405,
    4: 505,
    5: 606,
    6: 707,
    7: 810,
    8: 908,
    10: 1001,
}

STYLE_SOURCE_COLUMNS = {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 10,
    10: 10,
}

VISIBLE_ROW_CENTERS = {
    "walk_move_source": 216,
    "cannot_walk_source": 300,
    "open_door_source": 382,
    "locked_source": 466,
    "stairway_source": 550,
    "talk_source": 714,
    "pick_up_coat_source": 880,
    "place_hang_coat_source": 962,
    "use_interact_source": 1126,
}

ACTION_SOURCE_ROWS = {
    "walk_move": "walk_move_source",
    "open_door": "open_door_source",
    "exit_leave_room": "open_door_source",
    "stairs_up": "stairway_source",
    "stairs_down": "stairway_source",
    "inspect_look": "use_interact_source",
    "talk_converse": "talk_source",
    "pick_up_take": "pick_up_coat_source",
    "pick_up_coat": "pick_up_coat_source",
    "place_hang_coat": "place_hang_coat_source",
    "use_interact": "use_interact_source",
    "locked_cannot_use": "locked_source",
    "not_available_disabled": "cannot_walk_source",
}

CURSOR_ACTIONS = list(ACTION_SOURCE_ROWS.keys())


def main() -> int:
    if not SOURCE.exists():
        print(f"Missing source sheet: {SOURCE}", file=sys.stderr)
        return 1

    source = Image.open(SOURCE).convert("RGBA")
    generated = []

    for style_index in range(1, 11):
        source_column = STYLE_SOURCE_COLUMNS[style_index]
        style_dir = OUTPUT_ROOT / f"style_{style_index:02d}"
        style_dir.mkdir(parents=True, exist_ok=True)

        for action in CURSOR_ACTIONS:
            source_row = ACTION_SOURCE_ROWS[action]
            icon = extract_icon(
                source,
                VISIBLE_COLUMN_CENTERS[source_column],
                VISIBLE_ROW_CENTERS[source_row],
            )
            output_path = style_dir / f"{action}.png"
            icon.save(output_path)
            generated.append((style_index, action, output_path))

    build_contact_sheet(generated)
    print(f"Extracted {len(generated)} cursor icons into {OUTPUT_ROOT}")
    print(f"Wrote contact-sheet preview to {PREVIEW}")
    return 0


def extract_icon(source: Image.Image, center_x: int, center_y: int) -> Image.Image:
    left = int(center_x - CROP_WIDTH / 2)
    top = int(center_y - CROP_HEIGHT / 2)
    crop = source.crop((left, top, left + CROP_WIDTH, top + CROP_HEIGHT)).convert("RGBA")
    mask = foreground_mask(crop)

    bbox = mask.getbbox()
    if bbox is None:
        transparent = Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))
        return transparent

    cleaned = Image.new("RGBA", crop.size, (0, 0, 0, 0))
    cleaned.paste(crop, (0, 0), mask)

    content = cleaned.crop(padded_bbox(bbox, crop.size, 3))
    content_bbox = content.getbbox()
    if content_bbox is None:
        return Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))

    content = content.crop(content_bbox)
    width, height = content.size
    scale = min(ICON_INNER_SIZE / max(1, width), ICON_INNER_SIZE / max(1, height))
    next_size = (max(1, round(width * scale)), max(1, round(height * scale)))
    content = content.resize(next_size, Image.Resampling.LANCZOS)

    output = Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))
    output.alpha_composite(
        content,
        ((ICON_SIZE - next_size[0]) // 2, (ICON_SIZE - next_size[1]) // 2),
    )
    return remove_small_edge_specks(output)


def foreground_mask(image: Image.Image) -> Image.Image:
    pixels = image.load()
    width, height = image.size
    background = estimate_background(image)
    outside_background = Image.new("L", image.size, 0)
    outside_pixels = outside_background.load()
    queue = deque()

    for x in range(width):
        for y in (0, height - 1):
            if outside_pixels[x, y] == 0 and is_edge_background_pixel(pixels[x, y], background):
                outside_pixels[x, y] = 255
                queue.append((x, y))

    for y in range(height):
        for x in (0, width - 1):
            if outside_pixels[x, y] == 0 and is_edge_background_pixel(pixels[x, y], background):
                outside_pixels[x, y] = 255
                queue.append((x, y))

    while queue:
        px, py = queue.popleft()

        for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
            if nx < 0 or ny < 0 or nx >= width or ny >= height:
                continue
            if outside_pixels[nx, ny] != 0:
                continue
            if not is_edge_background_pixel(pixels[nx, ny], background):
                continue

            outside_pixels[nx, ny] = 255
            queue.append((nx, ny))

    mask = Image.new("L", image.size, 0)
    mask_pixels = mask.load()

    for y in range(height):
        for x in range(width):
            if pixels[x, y][3] != 0 and outside_pixels[x, y] == 0:
                mask_pixels[x, y] = 255

    mask = mask.filter(ImageFilter.MaxFilter(3))
    mask = fill_enclosed_holes(mask)
    mask = mask.filter(ImageFilter.GaussianBlur(0.45))
    return mask


def is_edge_background_pixel(pixel: tuple[int, int, int, int], background: tuple[int, int, int]) -> bool:
    r, g, b, a = pixel
    if a < 8:
        return True

    average = (r + g + b) / 3
    saturation = max(r, g, b) - min(r, g, b)
    background_delta = abs(r - background[0]) + abs(g - background[1]) + abs(b - background[2])

    return (
        background_delta < 92
        or (average > 168 and saturation < 118)
        or (r > 155 and g > 112 and b > 55 and average > 125 and saturation < 145)
    )


def estimate_background(image: Image.Image) -> tuple[int, int, int]:
    width, height = image.size
    samples = []
    pixels = image.load()

    for x in range(width):
        for y in (0, 1, height - 2, height - 1):
            r, g, b, a = pixels[x, y]
            if a:
                samples.append((r, g, b))

    for y in range(height):
        for x in (0, 1, width - 2, width - 1):
            r, g, b, a = pixels[x, y]
            if a:
                samples.append((r, g, b))

    if not samples:
        return (232, 210, 164)

    return (
        int(median(sample[0] for sample in samples)),
        int(median(sample[1] for sample in samples)),
        int(median(sample[2] for sample in samples)),
    )


def remove_edge_connected_components(mask: Image.Image) -> Image.Image:
    width, height = mask.size
    pixels = mask.load()
    visited = set()
    keep = Image.new("L", mask.size, 0)
    keep_pixels = keep.load()

    for y in range(height):
        for x in range(width):
            if pixels[x, y] == 0 or (x, y) in visited:
                continue

            component = []
            touches_edge = False
            queue = deque([(x, y)])
            visited.add((x, y))

            while queue:
                point = queue.popleft()
                px, py = point
                component.append(point)
                if px <= 1 or py <= 1 or px >= width - 2 or py >= height - 2:
                    touches_edge = True

                for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
                    if nx < 0 or ny < 0 or nx >= width or ny >= height:
                        continue
                    if pixels[nx, ny] == 0 or (nx, ny) in visited:
                        continue
                    visited.add((nx, ny))
                    queue.append((nx, ny))

            min_x = min(point[0] for point in component)
            max_x = max(point[0] for point in component)
            min_y = min(point[1] for point in component)
            max_y = max(point[1] for point in component)
            component_width = max_x - min_x + 1
            component_height = max_y - min_y + 1
            looks_like_horizontal_grid = component_width > width * 0.42 and component_height <= 5
            looks_like_vertical_grid = component_height > height * 0.42 and component_width <= 5
            looks_like_edge_speck = touches_edge and len(component) < 24

            if looks_like_horizontal_grid or looks_like_vertical_grid or looks_like_edge_speck:
                continue

            for px, py in component:
                keep_pixels[px, py] = 255

    if keep.getbbox() is None:
        return mask

    return keep


def fill_enclosed_holes(mask: Image.Image) -> Image.Image:
    width, height = mask.size
    binary = mask.point(lambda value: 255 if value > 0 else 0)
    pixels = binary.load()
    outside = Image.new("L", mask.size, 0)
    outside_pixels = outside.load()
    queue = deque()

    for x in range(width):
        for y in (0, height - 1):
            if pixels[x, y] == 0 and outside_pixels[x, y] == 0:
                outside_pixels[x, y] = 255
                queue.append((x, y))

    for y in range(height):
        for x in (0, width - 1):
            if pixels[x, y] == 0 and outside_pixels[x, y] == 0:
                outside_pixels[x, y] = 255
                queue.append((x, y))

    while queue:
        px, py = queue.popleft()
        for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
            if nx < 0 or ny < 0 or nx >= width or ny >= height:
                continue
            if pixels[nx, ny] != 0 or outside_pixels[nx, ny] != 0:
                continue
            outside_pixels[nx, ny] = 255
            queue.append((nx, ny))

    filled = Image.new("L", mask.size, 0)
    filled_pixels = filled.load()

    for y in range(height):
        for x in range(width):
            if pixels[x, y] != 0 or outside_pixels[x, y] == 0:
                filled_pixels[x, y] = 255

    return filled


def remove_small_edge_specks(image: Image.Image) -> Image.Image:
    width, height = image.size
    alpha = image.getchannel("A")
    pixels = alpha.load()
    visited = set()
    speck_boxes: list[tuple[int, int, int, int]] = []

    for y in range(height):
        for x in range(width):
            if pixels[x, y] <= 40 or (x, y) in visited:
                continue

            component = []
            queue = deque([(x, y)])
            visited.add((x, y))

            while queue:
                px, py = queue.popleft()
                component.append((px, py))

                for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
                    if nx < 0 or ny < 0 or nx >= width or ny >= height:
                        continue
                    if pixels[nx, ny] <= 40 or (nx, ny) in visited:
                        continue
                    visited.add((nx, ny))
                    queue.append((nx, ny))

            min_x = min(point[0] for point in component)
            max_x = max(point[0] for point in component)
            min_y = min(point[1] for point in component)
            max_y = max(point[1] for point in component)
            touches_outer_margin = min_x <= 6 or min_y <= 6 or max_x >= width - 7 or max_y >= height - 7

            if touches_outer_margin and len(component) < 90:
                speck_boxes.append((
                    max(0, min_x - 1),
                    max(0, min_y - 1),
                    min(width - 1, max_x + 1),
                    min(height - 1, max_y + 1),
                ))

    if not speck_boxes:
        return image

    cleaned = image.copy()
    cleaned_pixels = cleaned.load()

    for min_x, min_y, max_x, max_y in speck_boxes:
        for y in range(min_y, max_y + 1):
            for x in range(min_x, max_x + 1):
                r, g, b, _ = cleaned_pixels[x, y]
                cleaned_pixels[x, y] = (r, g, b, 0)

    return cleaned


def padded_bbox(bbox: tuple[int, int, int, int], size: tuple[int, int], padding: int) -> tuple[int, int, int, int]:
    left, top, right, bottom = bbox
    width, height = size
    return (
        max(0, left - padding),
        max(0, top - padding),
        min(width, right + padding),
        min(height, bottom + padding),
    )


def build_contact_sheet(generated: list[tuple[int, str, Path]]) -> None:
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    cell = 84
    label_height = 24
    left_label = 148
    width = left_label + 10 * cell
    height = label_height + len(CURSOR_ACTIONS) * cell
    sheet = Image.new("RGBA", (width, height), (22, 26, 20, 255))
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()

    draw.rectangle((0, 0, width - 1, height - 1), outline=(186, 145, 64, 255), width=2)
    for style_index in range(1, 11):
        x = left_label + (style_index - 1) * cell
        label = f"Style {style_index:02d}"
        if style_index == 9:
            label = "Style 09*"
        draw.text((x + 10, 6), label, fill=(240, 211, 131, 255), font=font)

    for row, action in enumerate(CURSOR_ACTIONS):
        y = label_height + row * cell
        draw.text((8, y + 31), action, fill=(240, 226, 178, 255), font=font)

        for style_index in range(1, 11):
            path = OUTPUT_ROOT / f"style_{style_index:02d}" / f"{action}.png"
            icon = Image.open(path).convert("RGBA")
            x = left_label + (style_index - 1) * cell
            draw.rectangle((x + 4, y + 4, x + cell - 4, y + cell - 4), outline=(93, 86, 58, 255), width=1)
            sheet.alpha_composite(icon, (x + 6, y + 6))

    draw.text(
        (left_label + 8 * cell + 8, height - 18),
        "*style 09 reuses visible sheet column 10",
        fill=(240, 211, 131, 255),
        font=font,
    )
    sheet.convert("RGB").save(PREVIEW)


if __name__ == "__main__":
    raise SystemExit(main())
